openapi: 3.1.0
info:
  title: Nozomi Alerts API
  description: OpenAPI specification for the Nozomi Alerts API
  version: 1.0.0
servers:
  - url: https://ernstyoung.customers.us1.vantage.nozominetworks.io
    description: Nozomi API Server
paths:
  /api/open/query/do:
    get:
      operationId: getAlerts
      summary: Retreave alerts from API
      parameters:
      responses:
        '200':
          description: Something happened
        '401':
          description: UnAuthorized           
        '500':
          description: Server error
