openapi: 3.1.0
info:
  title: Nozomi Alerts API
  description: OpenAPI specification for the Nozomi Alerts API
  version: 1.0.0
servers:
  - url: https://ernstyoung.customers.us1.vantage.nozominetworks.io
    description: Nozomi API Server
paths:
  /api/open/query/do?query=alerts | exclude bpf_filter properties description | where time >= hours_ago(24) | where !is_incident | where risk >= 7:
    get:
      operationId: getPointData
      summary: Retreave alerts from API
      parameters:
      responses:
        '200':
          description: Successfully retrieved alerts
          content:
            application/json:
              schema:
                type: object
                properties:
                  properties:
                    type: object
                    properties:
                      
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
